version: '3.8'

# Simplified docker-compose file optimized for local development
services:
  backend:
    build: ./backend
    container_name: researchapp-api-local
    volumes:
      - ./backend:/app
      # Mount the local directory to enable hot reloading
      - backend_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=${SECRET_KEY:-a8d4f7e6b3c2d1a8d4f7e6b3c2d1a8d4f7e6b3c2d1}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    command: >  
      sh -c "python -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    restart: always
    
  frontend:
    build: ./frontend
    container_name: researchapp-web-local
    volumes:
      - ./frontend:/app
      # Mount the local directory for React hot reloading
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    # Use create-react-app's development server for local dev
    command: npm start
    restart: always

volumes:
  backend_data: