version: '3.8'

services:
  db:
    image: postgres:13
    container_name: researchapp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_password}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-researchapp}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    
  backend:
    build: ./backend
    container_name: researchapp-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-your_password}@db:5432/${DB_NAME:-researchapp}
      - SECRET_KEY=${SECRET_KEY:-your_production_secret_key}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    restart: always
    
  frontend:
    build: ./frontend
    container_name: researchapp-web
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 