[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc", "glibc.dev", "postgresql"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python3 -c \"import os, sys; sys.path.append('.'); from database import engine; import models; models.Base.metadata.create_all(bind=engine); print('Database tables created successfully!')\""
]

[start]
cmd = "cd backend && chmod +x railway_start.sh && ./railway_start.sh" 