[phases.setup]
nixPkgs = ["python39", "gcc", "libc6-dev"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python -c 'print(\"Build successful!\")'"
]

[start]
cmd = "cd backend && chmod +x railway_start.sh && ./railway_start.sh" 