[phases.setup]
nixPkgs = ["python39", "python39Packages.virtualenv", "gcc", "glibc.dev", "postgresql"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "cd backend && python3 -m pip install --no-cache-dir -r requirements.txt"
]

# Do not create tables at build time - this will be handled by railway_start.sh
[phases.build]
cmds = [
  "echo 'Skipping table creation during build phase - will be handled at runtime'"
]

[start]
cmd = "cd backend && chmod +x railway_start.sh && ./railway_start.sh" 