[project]
name = "backend-api-project"

[deploy]
healthcheck_path = "/health"
healthcheck_timeout_seconds = 30
healthcheck_interval_seconds = 15
healthcheck_initial_delay_seconds = 15
strategy = "rolling"
restartPolicyType = "on_failure"

[[services]]
name = "backend-api"
root_directory = "backend"
# No dockerfile_path specified - will use Nixpacks for buildtime detection
start_command = "./railway_start.sh"  # Use our startup script
envs = [
  { name = "DATABASE_URL", value = "${RAILWAY_DATABASE_URL}" },
  { name = "SECRET_KEY", value = "${SECRET_KEY}" },
  { name = "ALGORITHM", value = "HS256" },
  { name = "ACCESS_TOKEN_EXPIRE_MINUTES", value = "30" },
  { name = "CORS_ORIGINS", value = "*" },
  { name = "PORT", value = "8080" }
]
internal_port = 8080
num_instances = 1
[services.http_route]
public_routes = ["/*"] 